### ISSUE TITLE
Suggest updating QCA to version 12.4, which has been tested very well!

### ISSUE THREAD

**Issue by zxlhhyccc** [bitthief/nss-packages#9]

**Comment by bitthief** [comment]
Hi,
Thanks for the heads-up, I already updated QCA SSDK and QCA SSDK Shell to 12.4 a few days ago, and it is stable indeed.

I'll be looking at updating the rest of the QCA packages / drivers over the next few days, the Qualcomm 6.1 support didn't look complete a few months ago, when I last looked at this. I'm not sure what the current situation is, but I suspect we're still going to need a lot of the existing patches (rebased, of course).
Patches and testing is very welcome, of course!
